services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - "1433:1433"

  app:
    build:
      context: ./ShoppingCart
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=ShoppingCart;User Id=sa;Password=Password123!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7055:7055"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
       VITE_API_URL: http://localhost:7055/api
    ports:
     - "5173:80"

volumes:
  mssql-data:
